# meta.yaml
# extra data needed for processing
#
# replacementTexts
#   theMaster
#     an array of edited replacements
#   stubs
#     each subkey will gather the words around it
#       without going beyond punctuation
#     until a string of suitable length is found
#     string of suitable length is sent to anagram generator
#     replacement is then selected
# bookNames
#   selected anagrams for each bookName
#   put favorite one at top

---
replacementTexts:
    theMaster:
        - ms Theatre
        - ms Theater
        - test Harem
        - met Earths
        - met Hearts
        - met Haters
        - me Hatters
        - me Shatter
        - me Threats
        - stem Hater
        - stem Heart
        - earth Stem
        - heats Term
        - haste Term
        - hates Term
        - hate Terms
        - heat Terms
        - the Stream
        - the Tamers
        - he Matters
        - eh Matters
        - she Matter
        - her Tamest
        - them Tears
        - them Rates
        - them Stare
        - hem Treats
        - hem Taster
        - mesh Treat
        - treat Hems
        - ham Street
        - ham Tester
        - ham Tetter
        - retest Ham
        - tree Maths
        - math Steer
        - reset Math
        - math Trees
        - terse Math
        - trash Meet
        - metre Hats
        - meter Hats
        - hat Meters
        - merest Hat
        - hat Metres
        - am Tethers
        - tethers Ma
        - mars Teeth
        - teeth Arms
        - there Mast
        - ether Mast
        - three Mast
        - mats There
        - ether Mats
        - three Mats
        - mat Ethers
        - mat Threes
        - star Theme
        - rats Theme
        - arts Theme
        - tsar Theme
        - rat Themes
        - art Themes
        - tar Themes
        - a ms Tether
        - a mrs Teeth
        - a rest Them
        - the a Terms
        - set mr Hate
        - set mr Heat
        - the ms Tear
        - rate the Ms
        - he ms Treat
        - eh ms Treat
        - the mr East
        - the mr Seat
        - the mr Teas
        - the mr Eats
        - he mr State
        - eh mr State
        - he mr Taste
        - eh mr Taste
        - eat the Mrs
        - ate the Mrs
        - the mrs Tea
        - set term Ha
        - met ha Rest
        - set ah Term
        - ah met Rest
        - mr hats Tee
        - tree ms Hat
        - mr tees Hat
        - mrs tee Hat
        - me rest Hat
        - that mr See
        - her am Test
        - am the Rest
        - her test Ma
        - the rest Ma
        - he test Arm
        - eh arm Test
        - the arm Set
        - test he Ram
        - eh ram Test
        - the set Ram
        - he mar Test
        - eh test Mar
        - the set Mar
        - he rest Mat
        - eh rest Mat
        - set her Mat
        - he met Star
        - eh met Star
        - me the Star
        - he met Rats
        - eh met Rats
        - me the Rats
        - he met Arts
        - eh met Arts
        - me the Arts
        - he met Tsar
        - eh met Tsar
        - me the Tsar
        - me start He
        - eh start Me
        - he me Tarts
        - eh me Tarts
        - he rat Stem
        - eh rat Stem
        - set hem Rat
        - she met Rat
        - he art Stem
        - eh stem Art
        - set hem Art
        - she met Art
        - he tar Stem
        - eh tar Stem
        - set tar Hem
        - she met Tar
        - she me Tart
        - as mr Teeth
        - as the Term
        - he sat Term
        - eh term Sat
        - met her Sat
        - ms at There
        - ms at Ether
        - ms at Three
        - mr at Sheet
        - mr at These
        - he at Terms
        - at eh Terms
        - hem at Rest
        - at her Stem
        - met at Hers
        - she at Term
        - he a mr Test
        - eh a test Mr
        - the set mr A
        - he set at Mr
        - eh at mr Set
    stubs:
        - virtue
        - said
        - of the
        - will
        - did not
        - in the
        - to be
        - prince
        - asked
bookNames:
    CONFUCIAN ANALECTS:
        - CANONICAL FACE STUN
        - CANONICAL SAFE CUNT
        - CANCAN UNFIT SOLACE
        - CON UNLACES FANATIC
        - CONCEAL SATANIC FUN
        - CONSISE ANNUAL FACT
        - FLAUNT COCAINE SCAN
        - CANCEL ANUS FACTION
        - CANCEL FAUN ACTIONS
        - CONCEAL FAUN ANTICS
        - ANNUL ACCENT FIASCO
        - FAT CONICAL NUANCES
        - LACONIC SUNTAN FACE
        - ENACTS LACONIC FAUN
        - CAN UNFASTEN CALICO
        - FINAL ACNE ACCOUNTS
        - ACE FUNCTIONAL SCAN
        - CONINTUAL FACE SCAN
        - TONICS FUEL A CANCAN
        - A FINE LOCUST CANCAN
        - A FAN CONCEALS TUNIC
        - A UNION CANCELS FACT
        - A COIF ANNULS ACCENT
        - A FUN CONICAL ASCENT
        - A FUN LACONIC STANCE
        - A CAUSTIC CANNON ELF
    WEI CHANG:
        - WING ACHE
        - EACH WING
        - WINCH AGE
    PA YIH:
        - HI PAY
        - YIP HA
    LE JIN:
        - NIJEL
    KUNG-YE CH'ANG:
        - HUNKY EGG CAN
        - NECK HANG GUY
        - ANY EGG CHUNK
        - YUCK HEN GANG
    YUNG YEY:
        - YE GUY NY
    SHU R:
        - RUSH
    T'AI-PO:
        - PATIO
        - ATOP I
        - I TO PA
    TSZE HAN:
        - ZEN HATS
    HEANG TANG:
        - THEN A GANG
        - HANG A GENT
        - TAN HEN GAG
        - TEN NAG HAG
    HSIEN TSIN:
        - I THINNESS
        - TINS SHINE
        - THINE SINS
        - THESIS INN
        - NINE SHITS
        - HIS TENNIS
        - SHIN INSET
        - ITS HEN SIN
        - SIT IN HENS
        - THEN IN SIN
        - THE SIS INN
        - HI IN NESTS
        - HIS IN NEST
        - IN HIS TENS
        - I SENT SHIN
        - HIS NET SIN
        - HISS IN NET
        - IN SHIN SET
    YEN YUAN:
        - UN YEA NY
    TSZE-LU:
        - LUTZES
        - ZUL SET
    HSIEN WAN:
        - WASH NINE
        - A HEN WINS
        - WHEN A SIN
        - A NEW SHIN
        - IN NEW ASH
        - SAW IN HEN
    WEI LING KUNG:
        - WINGLIKE GUN
        - WIN GLUE KING
        - WIG GUNK LINE
        - LUG WINE KING
        - I WIN GEL GUNK
        - WE LUG GIN KIN
    KE SHE:
        - SHEEK
    YANG HO:
        - OH YANG
        - ANY HOG
    WEI TSZE:
        - WEE ZITS
        - WET SIZE
    TSZE-CHANG:
        - CHEZ ANGST
        - CHEZ GNATS
        - ZEN TAGS CH
    YAO YUEH:
        - YEAH YOU
        - YO UH YEA
